name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt6-base-dev qt6-base-dev-tools \
            qt6-multimedia-dev qt6-multimedia-dev-tools libgl1-mesa-dev libpulse-dev patchelf wget

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j"$(nproc)"

      - name: Package AppImage
        run: scripts/package-appimage.sh "${GITHUB_REF_NAME}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obsbot-control-linux-${{ github.ref_name }}
          path: build/artifacts/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/artifacts/*
